apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config # An arbitrary name for the config map.
data: # Actual content of the config map (key-value pairs that we define as external configuration for the application.)
  mongo-url: mongo-service # Value will be service we create for mongodb application in kubernetes.